# Generated by Django 5.2 on 2025-04-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course_app', '0002_lesson_completion_status_lesson_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
